{
 "title": "Line Performance",
 "tags": [ "SmartFactory" ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "Site", "label": "Site", "query": "Select site from equipment" },
   {
    "name": "Area",
    "label": "Area",
    "query": "select area from equipment where area is not null and site = '$Site'"
   },
   {
    "name": "Line",
    "label": "Line",
    "query": "select production_line from equipment where production_line is not null and area = '$Area' and site = '$Site'"
   }
  ]
 },
 "panels": [
  {
   "title": "Current Running Order",
   "type": "libre-operator-order-mgt-table-panel",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "Select last_production_line as production_line,last_product_desc as product_desc, last_order_state as order_state,last_scheduled_start_datetime as scheduled_start_datetime,last_actual_start_datetime as actual_start_datetime,last_setpoint_rate as setpoint_rate,last_order_qty as order_qty,last_issued_qty as issued_qty, last_order_qty - last_issued_qty as remaining_qty ,(last_order_qty - last_issued_qty)/last_setpoint_rate as remaining_time FROM (SELECT last(*) FROM \"OrderPerformance\" GROUP BY \"order_id\",\"product_id\" ) WHERE \"last_order_state\" =~ /running|next/ and \"last_production_line\" = '$Site | $Area | $Line' GROUP BY \"order_id\",\"product_id\" ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Planned Production",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 4 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT integral(\"planned_rate\",1s)/3600 FROM \"Performance\" WHERE $timeFilter and (\"Site\" = '$Site') and (\"Area\" = '$Area')  and (\"Line\" = '$Line') ",
     "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    }
   ]
  },
  {
   "title": "Actual Production",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 4 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"actual_rate\") FROM \"Performance\" WHERE $timeFilter and (\"Site\" = '$Site') and (\"Area\" = '$Area')  and (\"Line\" = '$Line') ",
     "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    }
   ]
  },
  {
   "title": "Held Time",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 4 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT SUM(\"last\") FROM (SELECT last(\"held\") FROM \"Performance\" WHERE (\"Site\" = '$Site') and (\"Area\" = '$Area')  and (\"Line\" = '$Line') AND $timeFilter GROUP BY time(1s) fill(previous))",
     "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    }
   ]
  },
  {
   "title": "Running Time",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 4 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "measurement": "Performance",
     "query": "SELECT SUM(\"last\") FROM (SELECT last(\"execute\") FROM \"Performance\" WHERE (\"Site\" = '$Site') and (\"Area\" = '$Area')  and (\"Line\" = '$Line') AND $timeFilter GROUP BY time(1s) fill(previous))",
     "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    }
   ]
  },
  {
   "title": "Availability",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 4 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT SUM(\"execute\") / (SUM(\"held\")+SUM(\"execute\")) FROM (SELECT last(\"held\") AS held, last(\"execute\") AS execute FROM \"Performance\" WHERE (\"Site\" = '$Site') and (\"Area\" = '$Area')  and (\"Line\" = '$Line') AND $timeFilter GROUP BY time(1s) fill(previous))",
     "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    }
   ]
  },
  {
   "title": "Performance",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 4 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT integral(\"actual_rate\",1s) / (integral(\"planned_rate\",1s) + integral(\"held\",1s)) FROM \"Performance\" WHERE $timeFilter and (\"Site\" = '$Site') and (\"Area\" = '$Area')  and (\"Line\" = '$Line') ",
     "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    }
   ]
  },
  {
   "title": "Current Rate",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 6 },
   "targets": [
    {
     "measurement": "Performance",
     "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n",
     "tags": [
      { "key": "Site", "operator": "=~", "value": "/^$Site$/" },
      { "condition": "AND", "key": "Area", "operator": "=~", "value": "/^$Area$/" },
      { "condition": "AND", "key": "Line", "operator": "=~", "value": "/^$Line$/" }
     ]
    }
   ]
  },
  {
   "title": "Line Performance",
   "type": "graph",
   "gridPos": { "h": 7, "w": 19, "x": 5, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Held",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Performance",
     "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n",
     "tags": [
      { "key": "Site", "operator": "=~", "value": "/^$Site$/" },
      { "condition": "AND", "key": "Area", "operator": "=~", "value": "/^$Area$/" },
      { "condition": "AND", "key": "Line", "operator": "=~", "value": "/^$Line$/" }
     ]
    },
    {
     "alias": "Actual Rate",
     "measurement": "Performance",
     "select": [
      [
       { "params": [ "actual_rate" ], "type": "field" },
       { "params": [ "actual_rate" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "Site", "operator": "=~", "value": "/^$Site$/" },
      { "condition": "AND", "key": "Area", "operator": "=~", "value": "/^$Area$/" },
      { "condition": "AND", "key": "Line", "operator": "=~", "value": "/^$Line$/" }
     ]
    },
    {
     "alias": "Idle",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Performance",
     "select": [
      [
       { "params": [ "idle" ], "type": "field" },
       {
        "params": [],
        "type": "first"
       }
      ]
     ],
     "tags": [
      { "key": "Site", "operator": "=~", "value": "/^$Site$/" },
      { "condition": "AND", "key": "Area", "operator": "=~", "value": "/^$Area$/" },
      { "condition": "AND", "key": "Line", "operator": "=~", "value": "/^$Line$/" }
     ]
    },
    {
     "alias": "Execute",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Performance",
     "select": [
      [
       { "params": [ "execute" ], "type": "field" },
       {
        "params": [],
        "type": "first"
       }
      ]
     ],
     "tags": [
      { "key": "Site", "operator": "=~", "value": "/^$Site$/" },
      { "condition": "AND", "key": "Area", "operator": "=~", "value": "/^$Area$/" },
      { "condition": "AND", "key": "Line", "operator": "=~", "value": "/^$Line$/" }
     ]
    },
    {
     "alias": "Stopped",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Performance",
     "select": [
      [
       { "params": [ "stopped" ], "type": "field" },
       {
        "params": [],
        "type": "first"
       }
      ]
     ],
     "tags": [
      { "key": "Site", "operator": "=~", "value": "/^$Site$/" },
      { "condition": "AND", "key": "Area", "operator": "=~", "value": "/^$Area$/" },
      { "condition": "AND", "key": "Line", "operator": "=~", "value": "/^$Line$/" }
     ]
    },
    {
     "alias": "Complete",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Performance",
     "select": [
      [
       { "params": [ "complete" ], "type": "field" },
       {
        "params": [],
        "type": "first"
       }
      ]
     ],
     "tags": [
      { "key": "Site", "operator": "=~", "value": "/^$Site$/" },
      { "condition": "AND", "key": "Area", "operator": "=~", "value": "/^$Area$/" },
      { "condition": "AND", "key": "Line", "operator": "=~", "value": "/^$Line$/" }
     ]
    }
   ]
  },
  {
   "title": "DownTime Editor Table",
   "type": "libre-event-editor-table-panel",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"Site\", \"Area\", \"Line\", \"status\", \"execute\", \"held\", \"idle\", \"stopped\", \"complete\", \"category\", \"reason\", \"equipment\", \"comment\" FROM \"Availability\" WHERE $timeFilter AND (\"Site\" = '$Site') AND (\"Area\" = '$Area') AND (\"Line\" = '$Line')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}