{
 "title": "Performance Copy",
 "time": { "from": "now-1m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "RAM_Usage_Washing",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"plc_memory\")\nFROM \"MessagingPerformance\"\nWHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "  CPU_Washing",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"plc_cpu\")\nFROM \"MessagingPerformance\"\nWHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Plc_Latency",
   "type": "table",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 10 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT\n  COUNT(\"plc_latency\") AS \"Cantidad_Muestras\",\n  MEAN(\"plc_latency\") AS \"Promedio\",\n  MAX(\"plc_latency\") AS \"Máximo\",\n  MIN(\"plc_latency\") AS \"Mínimo\",\n  STDDEV(\"plc_latency\") AS \"Desv_Estandar\"\nFROM \"MessagingPerformance\"\nWHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "MQTT_Latency",
   "type": "table",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 10 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT\n  COUNT(\"latencia_ms\") AS \"Cantidad_Muestras\",\n  MEAN(\"latencia_ms\") AS \"Promedio\",\n  MAX(\"latencia_ms\") AS \"Máximo\",\n  MIN(\"latencia_ms\") AS \"Mínimo\",\n  STDDEV(\"latencia_ms\") AS \"Desv_Estandar\"\nFROM \"MessagingPerformance\"\nWHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Mensajes Recibidos",
   "type": "table",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 13 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT\nlast(\"porcentaje_recibidos\") AS \"recibidos %\",\ncount(\"porcentaje_recibidos\") AS \"Cantidad_Muestras\"\nFROM \"MessagingPerformance\"\nWHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Mensajes Perdidos",
   "type": "table",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 13 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT\nlast(\"porcentaje_perdidos\") AS \"Perdidos%\",\ncount(\"porcentaje_perdidos\") AS \"Cantidad_Muestras\"\nFROM \"MessagingPerformance\"\nWHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}